### PR TITLE
Replace (most of) merge-and-build.sh with a jenkins pipeline

### PR DESCRIPTION
**Pull request by bbguimaraes**
Initial version for review.  I'm sure there are many things that can be improved.

For testing, I'm using local clones of the official repositories, which works around the authentication problem for OSE (and speeds things up).  I'm going to figure out how to inject credentials for that next.

I also added the option to the `origin/master -> ose/master` merge to prefer changes from the latter in case of a conflict (`--strategy-option=theirs`), as Troy suggested.  That allows the build to execute to the end, as right now there is a conflict.

@jupierce: PTAL.

### CODE REVIEW

**Comment by bbguimaraes** [comment]
Solving the dependency problem is also future work.  I'm including them in the jenkins image for testing:

```Dockerfile
FROM openshift/jenkins-2-centos7@sha256:<latest digest>
USER root
RUN yum -y install epel-release \
    && pkgs='golang tito' \
    && yum -y install $pkgs \
    && rpm -q $pkgs
USER 1001
```

**Comment by jupierce** [comment]
@bbguimaraes Impressive start. Can you submit your PR against a branch I just created for your work: "build/ose-pipeline" . That will let us refine both bash & pipeline branches in parallel. Once the pipeline version works, we can get rid of the bash branch.

**Review by jupierce — COMMENTED** [review]
Please move this PR to buid/ose-pipeline . In this meantime, a quick review on its current state.

**Comment by jupierce** [comment]
@bbguimaraes  

- It may be useful to split the current stage(..){} up. Adding more stages (cloning, rpm build, image build, etc) doesn't have much functional impact, but will make the Jenkins UI provide better feedback as the stages progress.

- It might not buy us much right now, but also keep an eye out for where parallelism might help (https://www.cloudbees.com/blog/parallelism-and-distributed-builds-jenkins). Git clones?

- Considering moving repeated code (e.g. git user/email) into a function. Example function:
```
def version(text) {
  def matcher = text =~ '<version>(.+)</version>'
  matcher ? matcher[0][1] : null
}
```

**Comment by jupierce** [comment]
@bbguimaraes You might also consider multi-line sh in some areas.
```
sh '''#!/bin/bash
git config ...
git config ...
'''
```

**Comment by jupierce** [comment]
@bbguimaraes You may have already determined this, but the docker pipeline plugin is not installed on the e2e-jenkins instance. I've asked Ari to install it for us when he gets a chance. We can then see if the dependencies can be containerized.

**Comment by jupierce** [comment]
@bbguimaraes Just FYI: I've gotten docker working with the e2e-jenkins instance. Here is an example that is functional: https://github.com/jupierce/aos-cd-jobs/blob/build/playground/Jenkinsfile  . Not the --privileged flag is required because of the version of docker running on buildvm.

**Pull request merged**
